// <auto-generated />
using System;
using InsurancePolicyManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InsurancePolicyManagement.Migrations
{
    [DbContext(typeof(InsuranceManagementContext))]
    partial class InsuranceManagementContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InsurancePolicyManagement.Models.Claim", b =>
                {
                    b.Property<string>("ClaimId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AgentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("ApprovedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CauseOfDeath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ClaimAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ClaimNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimantBankDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimantName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ClaimantRelation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FiledDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvestigationNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RequiresInvestigation")
                        .HasColumnType("bit");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnderwriterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ClaimId");

                    b.HasIndex("AgentId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UnderwriterId");

                    b.HasIndex("UserId");

                    b.ToTable("Claims");

                    b.HasData(
                        new
                        {
                            ClaimId = "CLM001",
                            CauseOfDeath = "Natural",
                            ClaimAmount = 5000000m,
                            ClaimNumber = "CLM/2024/001",
                            ClaimType = "Death",
                            ClaimantBankDetails = "SBI Account: 12345678901",
                            ClaimantName = "Lakshmi Rajesh Reddy",
                            ClaimantRelation = "Spouse",
                            FiledDate = new DateTime(2024, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IncidentDate = new DateTime(2024, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyId = "POL001",
                            RequiresInvestigation = false,
                            Status = "Pending",
                            UserId = "USE001"
                        });
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.Document", b =>
                {
                    b.Property<string>("DocumentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ClaimId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FileHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("PolicyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProposalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VerificationNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DocumentId");

                    b.HasIndex("ClaimId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("ProposalId");

                    b.HasIndex("UserId");

                    b.ToTable("Documents");

                    b.HasData(
                        new
                        {
                            DocumentId = "DOC001",
                            DocumentType = 10,
                            FileName = "policy_POL001.pdf",
                            FilePath = "/uploads/documents/policy_POL001.pdf",
                            PolicyId = "POL001",
                            Status = 19,
                            UploadedAt = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "USE001",
                            VerifiedAt = new DateTime(2024, 1, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            DocumentId = "DOC003",
                            DocumentType = 4,
                            FileName = "medical_report_POS001.pdf",
                            FilePath = "/uploads/documents/medical_report_POS001.pdf",
                            ProposalId = "POS001",
                            Status = 19,
                            UploadedAt = new DateTime(2024, 4, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = "USE004",
                            VerifiedAt = new DateTime(2024, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.DocumentVerification", b =>
                {
                    b.Property<string>("VerificationId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("UnderwriterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("VerificationNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VerificationStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("VerificationId");

                    b.HasIndex("DocumentId");

                    b.HasIndex("UnderwriterId");

                    b.ToTable("DocumentVerifications");
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.Nominee", b =>
                {
                    b.Property<string>("NomineeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AadhaarNumber")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PolicyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProposalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Relationship")
                        .HasColumnType("int");

                    b.Property<decimal>("SharePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("NomineeId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("ProposalId");

                    b.ToTable("Nominees");

                    b.HasData(
                        new
                        {
                            NomineeId = "NOM001",
                            AadhaarNumber = "123456789017",
                            Address = "12-34, MG Road, Hyderabad, Telangana - 500001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1987, 6, 20),
                            FullName = "Lakshmi Rajesh Reddy",
                            PolicyId = "POL001",
                            Relationship = 1,
                            SharePercentage = 100m
                        },
                        new
                        {
                            NomineeId = "NOM002",
                            AadhaarNumber = "123456789018",
                            Address = "45-67, Anna Salai, Chennai, Tamil Nadu - 600002",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1988, 4, 15),
                            FullName = "Suresh Kumar Nair",
                            PolicyId = "POL002",
                            Relationship = 1,
                            SharePercentage = 60m
                        },
                        new
                        {
                            NomineeId = "NOM003",
                            AadhaarNumber = "123456789019",
                            Address = "45-67, Anna Salai, Chennai, Tamil Nadu - 600002",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(2015, 8, 10),
                            FullName = "Aadhya Priya Nair",
                            PolicyId = "POL002",
                            Relationship = 2,
                            SharePercentage = 40m
                        },
                        new
                        {
                            NomineeId = "NOM004",
                            AadhaarNumber = "123456789020",
                            Address = "78-90, Brigade Road, Bangalore, Karnataka - 560001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1984, 12, 3),
                            FullName = "Kavitha Venkatesh Iyer",
                            PolicyId = "POL003",
                            Relationship = 1,
                            SharePercentage = 100m
                        });
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.Payment", b =>
                {
                    b.Property<string>("PaymentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("NextDueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentGateway")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProposalId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PaymentId");

                    b.HasIndex("PolicyId");

                    b.HasIndex("UserId");

                    b.ToTable("Payments");

                    b.HasData(
                        new
                        {
                            PaymentId = "PAY001",
                            Amount = 22500m,
                            DueDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NextDueDate = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentGateway = "Razorpay",
                            PaymentMethod = "UPI",
                            PaymentType = "Premium",
                            PolicyId = "POL001",
                            ProcessedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Success",
                            TransactionId = "TXN001234567890",
                            UserId = "USE001"
                        },
                        new
                        {
                            PaymentId = "PAY002",
                            Amount = 45200m,
                            DueDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NextDueDate = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentGateway = "Paytm",
                            PaymentMethod = "NetBanking",
                            PaymentType = "Premium",
                            PolicyId = "POL002",
                            ProcessedDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Success",
                            TransactionId = "TXN001234567891",
                            UserId = "USE002"
                        },
                        new
                        {
                            PaymentId = "PAY003",
                            Amount = 38750m,
                            DueDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NextDueDate = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PaymentGateway = "Razorpay",
                            PaymentMethod = "Card",
                            PaymentType = "Premium",
                            PolicyId = "POL003",
                            ProcessedDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Success",
                            TransactionId = "TXN001234567892",
                            UserId = "USE003"
                        });
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.Policy", b =>
                {
                    b.Property<string>("PolicyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AgentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("IssuedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NextPremiumDue")
                        .HasColumnType("datetime2");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PolicyType")
                        .HasColumnType("int");

                    b.Property<decimal>("PremiumAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PremiumFrequency")
                        .HasColumnType("int");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SumAssured")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TermYears")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("PolicyId");

                    b.HasIndex("AgentId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Policies");

                    b.HasData(
                        new
                        {
                            PolicyId = "POL001",
                            ExpiryDate = new DateTime(2044, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NextPremiumDue = new DateTime(2025, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyNumber = "LIC/TERM/2024/001",
                            PolicyType = 0,
                            PremiumAmount = 22500m,
                            PremiumFrequency = 3,
                            ProductId = "PRD001",
                            StartDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            SumAssured = 5000000m,
                            TermYears = 20,
                            UserId = "USE001"
                        },
                        new
                        {
                            PolicyId = "POL002",
                            ExpiryDate = new DateTime(2044, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuedDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NextPremiumDue = new DateTime(2025, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyNumber = "LIC/END/2024/002",
                            PolicyType = 1,
                            PremiumAmount = 45200m,
                            PremiumFrequency = 3,
                            ProductId = "PRD002",
                            StartDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            SumAssured = 1000000m,
                            TermYears = 20,
                            UserId = "USE002"
                        },
                        new
                        {
                            PolicyId = "POL003",
                            ExpiryDate = new DateTime(2039, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IssuedDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NextPremiumDue = new DateTime(2025, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyNumber = "HDFC/ULIP/2024/003",
                            PolicyType = 2,
                            PremiumAmount = 38750m,
                            PremiumFrequency = 3,
                            ProductId = "PRD004",
                            StartDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            SumAssured = 2500000m,
                            TermYears = 15,
                            UserId = "USE003"
                        });
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.PolicyProduct", b =>
                {
                    b.Property<string>("ProductId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("BaseRate")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasDeathBenefit")
                        .HasColumnType("bit");

                    b.Property<bool>("HasMaturityBenefit")
                        .HasColumnType("bit");

                    b.Property<int>("InsuranceType")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxAge")
                        .HasColumnType("int");

                    b.Property<decimal>("MaxSumAssured")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxTerm")
                        .HasColumnType("int");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.Property<decimal>("MinSumAssured")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MinTerm")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("PolicyProducts");

                    b.HasData(
                        new
                        {
                            ProductId = "PRD001",
                            BaseRate = 4.5m,
                            Category = 0,
                            CompanyName = "LIC",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasDeathBenefit = true,
                            HasMaturityBenefit = false,
                            InsuranceType = 0,
                            IsActive = true,
                            MaxAge = 65,
                            MaxSumAssured = 10000000m,
                            MaxTerm = 30,
                            MinAge = 18,
                            MinSumAssured = 500000m,
                            MinTerm = 10,
                            ProductName = "Tech Term",
                            RiskLevel = 0
                        },
                        new
                        {
                            ProductId = "PRD002",
                            BaseRate = 45.2m,
                            Category = 1,
                            CompanyName = "LIC",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasDeathBenefit = true,
                            HasMaturityBenefit = true,
                            InsuranceType = 0,
                            IsActive = true,
                            MaxAge = 50,
                            MaxSumAssured = 5000000m,
                            MaxTerm = 35,
                            MinAge = 18,
                            MinSumAssured = 100000m,
                            MinTerm = 15,
                            ProductName = "Jeevan Anand",
                            RiskLevel = 0
                        },
                        new
                        {
                            ProductId = "PRD003",
                            BaseRate = 52.8m,
                            Category = 3,
                            CompanyName = "LIC",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasDeathBenefit = true,
                            HasMaturityBenefit = true,
                            InsuranceType = 0,
                            IsActive = true,
                            MaxAge = 45,
                            MaxSumAssured = 3000000m,
                            MaxTerm = 20,
                            MinAge = 13,
                            MinSumAssured = 100000m,
                            MinTerm = 20,
                            ProductName = "New Money Back 20",
                            RiskLevel = 0
                        },
                        new
                        {
                            ProductId = "PRD004",
                            BaseRate = 15.5m,
                            Category = 2,
                            CompanyName = "HDFC Life",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasDeathBenefit = true,
                            HasMaturityBenefit = true,
                            InsuranceType = 0,
                            IsActive = true,
                            MaxAge = 60,
                            MaxSumAssured = 25000000m,
                            MaxTerm = 30,
                            MinAge = 18,
                            MinSumAssured = 500000m,
                            MinTerm = 10,
                            ProductName = "Click2Wealth",
                            RiskLevel = 2
                        },
                        new
                        {
                            ProductId = "PRD005",
                            BaseRate = 85.5m,
                            Category = 4,
                            CompanyName = "LIC",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasDeathBenefit = true,
                            HasMaturityBenefit = true,
                            InsuranceType = 0,
                            IsActive = true,
                            MaxAge = 79,
                            MaxSumAssured = 10000000m,
                            MaxTerm = 40,
                            MinAge = 30,
                            MinSumAssured = 150000m,
                            MinTerm = 10,
                            ProductName = "Jeevan Shanti",
                            RiskLevel = 0
                        },
                        new
                        {
                            ProductId = "PRD008",
                            BaseRate = 3.5m,
                            Category = 6,
                            CompanyName = "HDFC ERGO",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasDeathBenefit = false,
                            HasMaturityBenefit = false,
                            InsuranceType = 1,
                            IsActive = true,
                            MaxAge = 75,
                            MaxSumAssured = 10000000m,
                            MaxTerm = 1,
                            MinAge = 18,
                            MinSumAssured = 50000m,
                            MinTerm = 1,
                            ProductName = "Comprehensive Motor Insurance",
                            RiskLevel = 1
                        },
                        new
                        {
                            ProductId = "PRD009",
                            BaseRate = 1.5m,
                            Category = 6,
                            CompanyName = "ICICI Lombard",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            HasDeathBenefit = false,
                            HasMaturityBenefit = false,
                            InsuranceType = 1,
                            IsActive = true,
                            MaxAge = 75,
                            MaxSumAssured = 0m,
                            MaxTerm = 1,
                            MinAge = 18,
                            MinSumAssured = 0m,
                            MinTerm = 1,
                            ProductName = "Third Party Motor Insurance",
                            RiskLevel = 0
                        });
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.Proposal", b =>
                {
                    b.Property<string>("ProposalId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AgentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("AnnualIncome")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Height")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<bool>("IsDrinker")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSmoker")
                        .HasColumnType("bit");

                    b.Property<string>("Occupation")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PreExistingConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PremiumAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PremiumFrequency")
                        .HasColumnType("int");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("SumAssured")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TermYears")
                        .HasColumnType("int");

                    b.Property<string>("UnderwritingNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Weight")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("ProposalId");

                    b.HasIndex("AgentId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Proposals");

                    b.HasData(
                        new
                        {
                            ProposalId = "POS001",
                            AnnualIncome = 800000m,
                            AppliedDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 165m,
                            IsDrinker = false,
                            IsSmoker = false,
                            Occupation = "Software Engineer",
                            PremiumAmount = 26400m,
                            PremiumFrequency = 3,
                            ProductId = "PRD003",
                            Status = 20,
                            SumAssured = 500000m,
                            TermYears = 20,
                            UserId = "USE004",
                            Weight = 60m
                        },
                        new
                        {
                            ProposalId = "POS002",
                            AnnualIncome = 1200000m,
                            AppliedDate = new DateTime(2024, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Height = 175m,
                            IsDrinker = true,
                            IsSmoker = false,
                            Occupation = "Business Analyst",
                            PremiumAmount = 85500m,
                            PremiumFrequency = 3,
                            ProductId = "PRD005",
                            Status = 21,
                            SumAssured = 1000000m,
                            TermYears = 25,
                            UserId = "USE005",
                            Weight = 75m
                        });
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.Quote", b =>
                {
                    b.Property<string>("QuoteId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AgentId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsConverted")
                        .HasColumnType("bit");

                    b.Property<decimal>("PremiumAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PremiumFrequency")
                        .HasColumnType("int");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("SumAssured")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("TermYears")
                        .HasColumnType("int");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("QuoteId");

                    b.HasIndex("AgentId");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("Quotes");
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.UnderwritingCase", b =>
                {
                    b.Property<string>("CaseId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApprovalConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ApprovedPremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("ApprovedSumAssured")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedUnderwriterId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CaseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Decision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DecisionReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequiredDocuments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RiskAssessment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UnderwriterNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("CaseId");

                    b.HasIndex("AssignedUnderwriterId");

                    b.HasIndex("UserId");

                    b.ToTable("UnderwritingCases");
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.User", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AadhaarNumber")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AgentAssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AssignedAgentId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssignedUnderwriterId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("KYCStatus")
                        .HasColumnType("int");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtpCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime2");

                    b.Property<string>("PANNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProfileImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UnderwriterAssignedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = "USE001",
                            AadhaarNumber = "123456789012",
                            Address = "12-34, MG Road, Hyderabad, Telangana - 500001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1985, 3, 15),
                            Email = "rajeshreddy@gmail.com",
                            FullName = "Rajesh Kumar Reddy",
                            Gender = 0,
                            IsActive = true,
                            KYCStatus = 1,
                            Mobile = "9876543210",
                            PANNumber = "ABCDE1234F",
                            Password = "Password123!",
                            Role = 0
                        },
                        new
                        {
                            UserId = "USE002",
                            AadhaarNumber = "123456789013",
                            Address = "45-67, Anna Salai, Chennai, Tamil Nadu - 600002",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1990, 7, 22),
                            Email = "priyanair@gmail.com",
                            FullName = "Priya Lakshmi Nair",
                            Gender = 1,
                            IsActive = true,
                            KYCStatus = 1,
                            Mobile = "9876543211",
                            PANNumber = "BCDEF2345G",
                            Password = "Password123!",
                            Role = 0
                        },
                        new
                        {
                            UserId = "USE003",
                            AadhaarNumber = "123456789014",
                            Address = "78-90, Brigade Road, Bangalore, Karnataka - 560001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1982, 11, 8),
                            Email = "venkateshiyer@gmail.com",
                            FullName = "Venkatesh Iyer",
                            Gender = 0,
                            IsActive = true,
                            KYCStatus = 1,
                            Mobile = "9876543212",
                            PANNumber = "CDEFG3456H",
                            Password = "Password123!",
                            Role = 1
                        },
                        new
                        {
                            UserId = "USE004",
                            AadhaarNumber = "123456789015",
                            Address = "23-45, Marine Drive, Kochi, Kerala - 682001",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1988, 5, 12),
                            Email = "meerakrishnan@gmail.com",
                            FullName = "Meera Krishnan",
                            Gender = 1,
                            IsActive = true,
                            KYCStatus = 0,
                            Mobile = "9876543213",
                            PANNumber = "DEFGH4567I",
                            Password = "Password123!",
                            Role = 3
                        },
                        new
                        {
                            UserId = "USE005",
                            AadhaarNumber = "123456789016",
                            Address = "56-78, IT Corridor, Tirupathi, Andhra Pradesh - 500081",
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateOfBirth = new DateOnly(1992, 9, 25),
                            Email = "jytohireddy@gmail.com",
                            FullName = "Jyothi Reddy",
                            Gender = 0,
                            IsActive = true,
                            KYCStatus = 1,
                            Mobile = "9876543214",
                            PANNumber = "EFGHI5678J",
                            Password = "Admin123!",
                            Role = 2
                        });
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.Claim", b =>
                {
                    b.HasOne("InsurancePolicyManagement.Models.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InsurancePolicyManagement.Models.Policy", "Policy")
                        .WithMany("Claims")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InsurancePolicyManagement.Models.User", "Underwriter")
                        .WithMany()
                        .HasForeignKey("UnderwriterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InsurancePolicyManagement.Models.User", "User")
                        .WithMany("Claims")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Policy");

                    b.Navigation("Underwriter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.Document", b =>
                {
                    b.HasOne("InsurancePolicyManagement.Models.Claim", "Claim")
                        .WithMany("Documents")
                        .HasForeignKey("ClaimId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InsurancePolicyManagement.Models.Policy", "Policy")
                        .WithMany("Documents")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InsurancePolicyManagement.Models.Proposal", "Proposal")
                        .WithMany("Documents")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InsurancePolicyManagement.Models.User", "User")
                        .WithMany("Documents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Claim");

                    b.Navigation("Policy");

                    b.Navigation("Proposal");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.DocumentVerification", b =>
                {
                    b.HasOne("InsurancePolicyManagement.Models.Document", "Document")
                        .WithMany()
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InsurancePolicyManagement.Models.User", "Underwriter")
                        .WithMany()
                        .HasForeignKey("UnderwriterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Document");

                    b.Navigation("Underwriter");
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.Nominee", b =>
                {
                    b.HasOne("InsurancePolicyManagement.Models.Policy", "Policy")
                        .WithMany("Nominees")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InsurancePolicyManagement.Models.Proposal", "Proposal")
                        .WithMany("Nominees")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Policy");

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.Payment", b =>
                {
                    b.HasOne("InsurancePolicyManagement.Models.Policy", "Policy")
                        .WithMany("Payments")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InsurancePolicyManagement.Models.User", "User")
                        .WithMany("Payments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Policy");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.Policy", b =>
                {
                    b.HasOne("InsurancePolicyManagement.Models.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InsurancePolicyManagement.Models.PolicyProduct", "Product")
                        .WithMany("Policies")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InsurancePolicyManagement.Models.User", "User")
                        .WithMany("Policies")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.Proposal", b =>
                {
                    b.HasOne("InsurancePolicyManagement.Models.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InsurancePolicyManagement.Models.PolicyProduct", "Product")
                        .WithMany("Proposals")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InsurancePolicyManagement.Models.User", "User")
                        .WithMany("Proposals")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.Quote", b =>
                {
                    b.HasOne("InsurancePolicyManagement.Models.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InsurancePolicyManagement.Models.PolicyProduct", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InsurancePolicyManagement.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.UnderwritingCase", b =>
                {
                    b.HasOne("InsurancePolicyManagement.Models.User", "AssignedUnderwriter")
                        .WithMany()
                        .HasForeignKey("AssignedUnderwriterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InsurancePolicyManagement.Models.User", "User")
                        .WithMany("UnderwritingCases")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedUnderwriter");

                    b.Navigation("User");
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.Claim", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.Policy", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Documents");

                    b.Navigation("Nominees");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.PolicyProduct", b =>
                {
                    b.Navigation("Policies");

                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.Proposal", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Nominees");
                });

            modelBuilder.Entity("InsurancePolicyManagement.Models.User", b =>
                {
                    b.Navigation("Claims");

                    b.Navigation("Documents");

                    b.Navigation("Payments");

                    b.Navigation("Policies");

                    b.Navigation("Proposals");

                    b.Navigation("UnderwritingCases");
                });
#pragma warning restore 612, 618
        }
    }
}
